runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main.app:app

runtime_config:
  python_version: 3


#[START env]
env_variables:
  CLOUD_STORAGE_BUCKET:  tomazwang-176210.appspot.com
#[END env]