runtime: python
env: flex
manual_scaling:
  instances: 1

#resources:
#  cpu: .5
#  memory_gb: 0.18
#  disk_size_gb: 10

entrypoint: gunicorn -b :$PORT main.app:app

runtime_config:
  python_version: 3


#[START env]
env_variables:
  CLOUD_STORAGE_BUCKET:  tomazwang-176210.appspot.com
#[END env]